In [1]:
import pandas as pd
import scipy as sp
import scipy.stats as stats

In [5]:
df = pd.read_csv("golf.csv", encoding="shift-jis")
df

   天気  気温  湿度  風  ゴルフ
0   晴  29  85  弱  しない
1   晴  27  90  強  しない
2   曇  28  78  弱   する
3   雨  21  96  弱   する
4   雨  20  80  弱   する
5   雨  18  70  強  しない
6   曇  18  65  強   する
7   晴  22  95  弱  しない
8   晴  21  70  弱   する
9   雨  24  80  弱   する
10  晴  24  70  強   する
11  曇  22  90  強   する
12  曇  27  75  弱   する
13  雨  22  80  強  しない

In [6]:
cross = pd.crosstab(df.ゴルフ, [df.天気, df.風])
cross

天気   晴     曇     雨
風    弱  強  弱  強  弱  強
ゴルフ
しない  2  1  0  0  0  2
する   1  1  2  2  3  0

In [7]:
x2, p, dof, expected = sp.stats.chi2_contingency(cross)

In [8]:
print(p)

0.11235865025855099

In [9]:
dfe = pd.DataFrame(expected)
dfe.columns = cross.columns
dfe

天気         晴                   曇                   雨
風          弱         強         弱         強         弱         強
0   1.071429  0.714286  0.714286  0.714286  1.071429  0.714286
1   1.928571  1.285714  1.285714  1.285714  1.928571  1.285714

In [10]:
dof

5

In [11]:
diff = cross - expected

In [12]:
dfa = pd.DataFrame(diff)
dfa.columns = cross.columns
dfa

天気          晴                   曇                   雨
風           弱         強         弱         強         弱         強
ゴルフ
しない  0.928571  0.285714 -0.714286 -0.714286 -1.071429  1.285714
する  -0.928571 -0.285714  0.714286  0.714286  1.071429 -1.285714